version: "3.1"

services:
  # include all information in test and
  # add the command to run
  app:
    image: nginx:alpine
    ports:
      - 8080:80 # ***update value here
    volumes:
      - ./app:/usr/share/nginx/html
