apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
    component: web
spec:
  selector:
    matchLabels:
      app: homepage
      component: web
  template:
    metadata:
      labels:
        app: homepage
        component: web
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: homepage
          image: ghcr.io/devxp-tech/homepage:devspace
          # image: diegoluisi/homepage

          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "10m"
              memory: "20Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
